Feature/authenticate login functionality
abdulhaqshah/be-prepared-app-bk pull request #3
Opened 2019-05-02 07:35 UTC by HarisShahidHameed

Trello : https://trello.com/b/FTaaANh4/be-prepared-application

2019-05-08 07:21 UTC, abdulhaqshah requested changes

2019-05-08 07:21 UTC, abdulhaqshah commented on server/DataBase/models/tokens.js
> +
extra lines

2019-05-08 07:21 UTC, abdulhaqshah commented on server/libs/userlibs.js
> +        if(!userData.name) {
make validation function and handle all that in it

2019-05-08 07:21 UTC, abdulhaqshah commented on server/libs/userlibs.js
> +            reject({
revamp this functionality

2019-05-08 07:21 UTC, abdulhaqshah commented on server/libs/userlibs.js
> +const login = function(body){
spce

2019-05-08 07:21 UTC, abdulhaqshah commented on server/libs/userlibs.js
> +                    let access = 'authentication';
constant

2019-05-08 07:21 UTC, abdulhaqshah commented on server/libs/userlibs.js
> +                        status : statusCodes.forbidden,
camel case

2019-05-08 07:21 UTC, abdulhaqshah commented on server/libs/userlibs.js
> +        if(error){
space

2019-05-08 07:21 UTC, abdulhaqshah commented on server/libs/userlibs.js
> +    let error = fieldsValidator(body);
nameing convention

2019-05-08 07:21 UTC, abdulhaqshah commented on server/middleware/authenticate.js
> +        return Promise.reject({status : statusCodes.unauthorized, message : messages.unauthorized});
do it with res on every promise

2019-05-08 07:21 UTC, abdulhaqshah commented on server/middleware/authenticate.js
> +    return Promise.reject({status : statusCodes.unauthorized, message : messages.unauthorized});
why Promise.return

2019-05-08 12:07 UTC, HarisShahidHameed commented on server/DataBase/models/tokens.js
> +
Removed.

2019-05-08 12:07 UTC, HarisShahidHameed commented on server/libs/userlibs.js
> +        if(!userData.name) {
Done that.

2019-05-08 12:07 UTC, HarisShahidHameed commented on server/libs/userlibs.js
> +            reject({
Done

2019-05-08 12:07 UTC, HarisShahidHameed commented on server/libs/userlibs.js
> +const login = function(body){
Given space.

2019-05-08 12:07 UTC, HarisShahidHameed commented on server/libs/userlibs.js
> +                    let access = 'authentication';
Done that. Move the secret key to constants.js and calling it from there

2019-05-08 12:08 UTC, HarisShahidHameed commented on server/libs/userlibs.js
> +                        status : statusCodes.forbidden,
Done

2019-05-08 12:08 UTC, HarisShahidHameed commented on server/libs/userlibs.js
> +        if(error){
Given space.

2019-05-08 12:08 UTC, HarisShahidHameed commented on server/libs/userlibs.js
> +    let error = fieldsValidator(body);
Done.

2019-05-08 12:08 UTC, HarisShahidHameed commented on server/middleware/authenticate.js
> +        return Promise.reject({status : statusCodes.unauthorized, message : messages.unauthorized});
Done that.

2019-05-08 12:08 UTC, HarisShahidHameed commented on server/middleware/authenticate.js
> +    return Promise.reject({status : statusCodes.unauthorized, message : messages.unauthorized});
So that .catch will catch these objects and return as error.

2019-05-08 12:11 UTC, abdulhaqshah requested changes

2019-05-08 12:11 UTC, abdulhaqshah commented on .eslintrc.json
> +        "init-declarations": "off",
revert these changes why they are off

2019-05-08 12:11 UTC, abdulhaqshah commented on server/DataBase/models/tokens.js
> +    token : String,
make this a requried field

2019-05-08 12:11 UTC, abdulhaqshah commented on server/libs/userlibs.js
> +        if(result) {
if should be like this if () {

2019-05-08 12:11 UTC, abdulhaqshah commented on server/libs/userlibs.js
> +        let result = fieldsValidator(userData);
change this into `fieldsValidate`

2019-05-09 07:02 UTC, HarisShahidHameed commented on .eslintrc.json
> +        "init-declarations": "off",
Done

2019-05-09 07:02 UTC, HarisShahidHameed commented on server/DataBase/models/tokens.js
> +    token : String,
Done

2019-05-09 07:02 UTC, HarisShahidHameed commented on server/libs/userlibs.js
> +        if(result) {
done

2019-05-09 07:03 UTC, HarisShahidHameed commented on server/libs/userlibs.js
> +        let result = fieldsValidator(userData);
Done

2019-05-09 07:37 UTC, abdulhaqshah requested changes

2019-05-09 07:37 UTC, abdulhaqshah commented on server/middleware/authenticate.js
> +
remove space

2019-05-09 07:37 UTC, abdulhaqshah commented on server/middleware/authenticate.js
> +    if(!isEmpty(req.params)) {
remove

2019-05-09 07:37 UTC, abdulhaqshah commented on server/middleware/authenticate.js
> +
extra line

2019-05-09 08:12 UTC, HarisShahidHameed commented on server/middleware/authenticate.js
> +
Removed.

2019-05-09 08:12 UTC, HarisShahidHameed commented on server/middleware/authenticate.js
> +    if(!isEmpty(req.params)) {
Removed.

2019-05-09 08:12 UTC, HarisShahidHameed commented on server/middleware/authenticate.js
> +
Removed

2019-05-09 09:53 UTC, abdulhaqshah approved these changes

2019-05-09 09:53 UTC, merged