Feature/change password functionality
abdulhaqshah/be-prepared-app-bk pull request #6
Opened 2019-05-15 07:36 UTC by HarisShahidHameed

Trello link : https://trello.com/c/0YdEhms0/20-changing-password-functionality

2019-05-15 08:01 UTC, abdulhaqshah requested changes

2019-05-15 08:01 UTC, abdulhaqshah commented on server/libs/userlibs.js
> +                User.findOneAndUpdate({uuid : body.uuid, deleted : false}, {$set : {password : body.password}}, {new: true}).then((user) => {
.then should b in next line

2019-05-15 08:01 UTC, abdulhaqshah commented on server/routes/user.js
> +    userLibs.changePassword(req).then((success) => {
req should not be sent as a parameter

2019-05-15 08:01 UTC, abdulhaqshah commented on server/libs/userlibs.js
> +                User.findOneAndUpdate({uuid : body.uuid, deleted : false}, {$set : {password : body.password}}, {new: true}).then((user) => {
deactivate check instead of delete

2019-05-15 08:01 UTC, abdulhaqshah commented on server/libs/userlibs.js
> +                            data : user
why are we sending user

2019-05-15 08:01 UTC, abdulhaqshah commented on server/libs/userlibs.js
> +                            data : user
don't need to send whole user object just a new password only

2019-05-17 10:14 UTC, HarisShahidHameed commented on server/libs/userlibs.js
> +                            data : user
Done

2019-05-17 10:14 UTC, HarisShahidHameed commented on server/routes/user.js
> +    userLibs.changePassword(req).then((success) => {
Done

2019-05-17 10:14 UTC, HarisShahidHameed commented on server/libs/userlibs.js
> +                User.findOneAndUpdate({uuid : body.uuid, deleted : false}, {$set : {password : body.password}}, {new: true}).then((user) => {
Done

2019-05-17 10:58 UTC, abdulhaqshah approved these changes

2019-05-17 10:58 UTC, merged